codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 0%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "src/**/*.spec.ts"
  - "src/**/*.integration.spec.ts"
  - "src/shared/testing/**"
  - "src/server.ts"
  - "**/*.d.ts"
