@token = 

###Obtener todas los alumnos
GET http://localhost:3000/api/students
Authorization: Bearer {{token}}

###Obtener un alumno (id: a02b91bc-3769-4221-beb1-d7a3aeba7dad)
GET http://localhost:3000/api/students/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Authorization: Bearer {{token}}

###Crear un alumno
# @prompt name
# @prompt surname
# @prompt mail
POST http://localhost:3000/api/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "{{name}}",
    "surname": "{{surname}}",
    "mail": "{{mail}}",
    "profile_picture": "noPhoto"
}

###Crear un alumno - rápido
POST http://localhost:3000/api/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Carlos",
    "surname": "Gugliermino",
    "mail": "carlosRichard@gmail.com",
    "profile_picture": "noPhoto"
}

###Modificar un alumno existente (PUT) 
PUT http://localhost:3000/api/students/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Lucas",
    "surname": "Trincavelli",
    "mail": "lucatrincavelli@gmail.com",
    "profile_picture": "noPhoto"
}

###Modificar un alumno existente (PATCH)
PATCH http://localhost:3000/api/students/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "surname": "Pedemonte"
}

###Borrar un alumno
DELETE http://localhost:3000/api/students/686d7a5c46c27757b7f72ba1
Authorization: Bearer {{token}}