@token = 

###Obtener todas los profesores
GET http://localhost:3000/api/professors
Authorization: Bearer {{token}}

###Obtener un profesor (id: a02b91bc-3769-4221-beb1-d7a3aeba7dad)
GET http://localhost:3000/api/professors/686c0cca07fd2bcda26f8117
Authorization: Bearer {{token}}

###Crear un profesor - rápido
POST http://localhost:3000/api/professors
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Carlos",
    "surname": "Xavier",
    "mail": "CXavier@gmail.com",
    "profile_picture": "noPhoto",
    "state": "accepted",
    "institution": "686c1b7668e202f38df086c8"
}

###Modificar un profesor existente (PUT) 
PUT http://localhost:3000/api/professors/a02b91bc-6769-4221-beb1-d7a3aeba7dac
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Pablo",
    "surname": "Sabatinelli",
    "mail": "PSab@gmail.com",
    "profile_picture": "noPhoto",
    "state": "accepted"
}

###Modificar un profesor existente (PATCH)
PATCH http://localhost:3000/api/professors/a02b91dc-3769-4221-beb1-d7a3aeba7dac
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "surname": "Milardovich"
}

###Borrar un profesor
DELETE http://localhost:3000/api/professors/686d8986b5844246c6494e31
Authorization: Bearer {{token}}
