@token = 

###Obtener todas las aplicaciones
GET http://localhost:3000/api/appeals
Authorization: Bearer {{token}}

###Obtener una aplicación
GET http://localhost:3000/api/appeals/689e15eb630aa739c3d58cb9
Authorization: Bearer {{token}}

###Crear una aplicación - rápido
POST http://localhost:3000/api/appeals
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "text": "Quiero que me acepten la solicitud porfis"
}


###Modificar una aplicación existente (PATCH)
PATCH http://localhost:3000/api/appeals/689e2a19c154d0575d785562
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "state": "accepted"
}

###Borrar una aplicación
DELETE http://localhost:3000/api/appeals/689e2a19c154d0575d785562
Authorization: Bearer {{token}}